### ISSUE TITLE
Script fails behind proxy

### ISSUE THREAD

**Issue by ojmakke** [lordmilko/i686-elf-tools#1]
You can change all the sudo ... commands to sudo -E ... to use the environmental variables setup in the shell, in case proxy is not set system wide.

**Comment by lordmilko** [comment]
Hi @ojmakke,

Thanks for raising this issue. I have now uploaded a new version of the script that specifies -E for all sudo commands that require network access.

In addition, the repo now includes precompiled binaries for Win32 and Linux using the latest versions of GCC/Binutils/GDB. Most importantly, the Win32 binaries now include libgcc! If you haven't managed to get a toolchain up and running with the latest versions of everything + libgcc I would strongly recommend giving the precompiled binaries a go.

Let me know if you have any issues!

Regards,
lordmilko
