### ISSUE TITLE
Bad system call (core dumped)

### ISSUE THREAD

**Issue by sasdallas** [lordmilko/i686-elf-tools#12]
Hello!

I have recently downloaded an i686 toolchain from your Releases page, and extracted it to a directory.

However, when I go into the bin/ directory and run any program, I get an error. The error is `Bad system call (core dumped)`. I don’t know why.

Thanks!

System Info:
Ubuntu 20.04 x86_64
(Running in Docker container)

**Comment by lordmilko** [comment]
Hi @sasdallas,

Are you able to confirm what OS both the host and Docker container are running?

**Comment by sasdallas** [comment]
@lordmilko I can confirm `/etc/os-release` states Ubuntu, I don't know about Docker version.

**Comment by lordmilko** [comment]
Are you saying the host OS is Ubuntu? What OS does the `Dockerfile` say the container will be using

**Comment by sasdallas** [comment]
@lordmilko I’m not sure, I know the Docker container being used, it’s `gitpod/workspace-full`. If required, I can create a Dockerfile

**Comment by sasdallas** [comment]
@lordmilko Issue fixed! I had to manually compile them, release didn’t work for me. Thanks!
