### ISSUE TITLE
error trying to exec 'cc1': execvp: No such file or directory

### ISSUE THREAD

**Issue by ghost** [lordmilko/i686-elf-tools#15]
Hey, so I downloaded the binaries of i686-elf-tools-linux, copied them to /usr/local and tried to compile my kernel.c, but I keep on getting this error "error trying to exec 'cc1': execvp: No such file or directory".

OS:
Debian 11.3.0 (it also happenes on CentOS Stream 8)

**Comment by lordmilko** [comment]
Hi @BlakeU666-pog,

Are you able to confirm whether you extracted all of the files in the zip to `/usr/local`? i.e. does the file `/usr/local/libexec/gcc/i686-elf/7.1.0/cc1` exist? (I believe that would be the path)

If so, what happens if you `chmod +x` that file?

**Comment by ghost** [comment]
I forgot about libexec, however I am getting several errors now from simple kernel.c script from Bare bones section on OSDev wiki (I believe the i686-elf-tools cross compiler was made specifically for the OSDev wiki) so there's something wrong with the cross compiler.

**Comment by lordmilko** [comment]
Please ensure you copy *all* of the files from the zip to `/usr/local`. You can also try extracting the zip to a random folder and attempting to run i686-elf-gcc from there; this will tell you if there's something wrong with the copy you've placed in `/usr/local`

**Comment by ghost** [comment]
Hm, after I extracted it to a folder in home, it worked now. Maybe I'll try to reextract it then. Thanks.

**Comment by ghost** [comment]
Alright, I reextracted the zip in /usr/local and everything works now. Thanks :)
