### ISSUE TITLE
Missing requirement: mako-render

### ISSUE THREAD

**Issue by joshua-jerred** [lordmilko/i686-elf-tools#16]
Leaving there here for anyone else that has this issue. When running the script in Ubuntu with WSL I was getting this error when the script was installing MXE.
`[check reqs]
Missing requirement: mako-render`

To correct the issue I installed python3-mako with
`sudo apt install python3-mako`
Then for the script to run again without issue, I had to delete /opt/mxe/ as the script would exit with the error
`fatal: destination path 'mxe' already exists and is not an empty directory.`
Removed with 
`sudo rm -r /opt/mxe/`

Hope this helps someone!

Edit:
This is in the readme, other prereqs might be needed for MXE.
https://mxe.cc/#requirements

**Comment by lordmilko** [comment]
Thanks @joshua-jerred,

Sounds like this is a prerequisite that has been added in newer versions of MXE; I have updated the script accordingly
