### ISSUE TITLE
finalize function should check to see if output directories exist

### ISSUE THREAD

**Issue by lurkermike** [lordmilko/i686-elf-tools#2]
The finalize function should check to see if the windows or linux output directories exist before trying to zip the files.

If I pass "linux" as a command-line option, I get the following error, because the windows output directory does not exist:

> ./i686-elf-tools.sh: line 291: cd: /home/mike/build-i686-elf/windows/output: No such file or directory

This seems to fix the problem:

```
function finalize {
    if [[ $args == *"zip"* ]]; then
        echo "Zipping everything up!"

        if [[ -d "$BUILD_DIR/windows/output" ]]; then
            cd $BUILD_DIR/windows/output
            zip -r $BUILD_DIR/i686-elf-tools-windows.zip *
        fi

        if [[ -d "$BUILD_DIR/linux/output" ]]; then
            cd $BUILD_DIR/linux/output
            zip -r $BUILD_DIR/i686-elf-tools-linux.zip *
        fi

        echo -e "\e[92mZipped everything to $BUILD_DIR/i686-elf-tools-[windows | linux].zip\e[39m"
    else
        echoColor "    Skipping zipping 'zip' was ommitted from commandline args '$args'"
    fi
}
```

**Comment by lordmilko** [comment]
Hi @lurkermike,

Great point! I will update the script and update this issue when this has been completed

Regards,
lordmilko

**Comment by lordmilko** [comment]
Hi @lurkermike,

This issue should now been resolved. Thanks for raising this issue

Regards,
lordmilko
