### ISSUE TITLE
Missing standard headers, startup-code, libc ?

### ISSUE THREAD

**Issue by Webfra** [lordmilko/i686-elf-tools#8]
Hello,
I'm sure this is not really an "issue", just my own ignorance. So I apologize in advance.

But where do I get the standard header files, startup-code (crt0.o) and the standard c library?
Do I have to cross-build them myself? Any hints available how to do this?

As the docker image has everything ready to build the cross-compiler, building the startup-code and standard c library could be built as well?
Or maybe the files can just be copied from the docker image? (Or would that not be advised?)

And help or pointers in the right direction would be appreciated!

**Comment by lordmilko** [comment]
Hi @Webfra,

My understanding is that you are supposed to write a standard library yourself

> One thing up front: When you begin working on your kernel, you do not have a C library available. You have to provide everything yourself, except a few pieces provided by the compiler itself. You will also have to port an existing C library or write one yourself.

https://wiki.osdev.org/How_kernel,_compiler,_and_C_library_work_together

In addition, you may wish to look at

* https://wiki.osdev.org/C_Library - provides examples of existing standard libraries people have written for use with operating system development
* https://wiki.osdev.org/Creating_a_C_Library - information on how to write your own standard library, including info about writing a crt0.o file

In my case, I implemented everything I need myself; solving challenges like how `printf` works is half the fun! Overall though, it is recommended you have a look at the OSDev wiki for potential strategies on how to proceed

Regards,
lordmilko

**Comment by Webfra** [comment]
Hi lordmilko,
Thanks for the quick reply. This looks like what I needed!
Regards,
Webfra
